### PR TITLE
Bring Lua to 5.4.6.

### PR DESCRIPTION
**Pull request by michaellenaghan**
The upstream Lua 5.4.5 to 5.4.6 diff is [here](https://github.com/lua/lua/compare/v5.4.5..v5.4.6).

The Cosmo Lua 5.4.5 to 5.4.6 diff is [here](https://github.com/michaellenaghan/cosmopolitan/compare/patch-lua-545..michaellenaghan:cosmopolitan:patch-lua-546).

===

You can either apply the pull requests step by step, or just this one. In my opinion, step by step is better; the work was already done, and the first two changes are complicated. I think the intermediate steps are like an insurance policy; most of the time you never need insurance, but when things go wrong…

### CODE REVIEW

**Comment by michaellenaghan** [comment]
In case it isn't obvious: the "Cosmo Lua 5.4.x to 5.4.y" links I've given show *only* the changes from .x to .y. The "Files changed" in the pull request, by contrast, show changes from master.

**Comment by pkulchenko** [comment]
@michaellenaghan, the patch for 5.4.6 looks good to me. Can you rebase against the current master (as there were several dlopen-related changes that created a conflict)? Thank you!

**Comment by michaellenaghan** [comment]
@pkulchenko Sorry, Paul; I tried to get to this before we leave, but it looks like I've run out of time. (The conflicts aren't, for the most part, difficult, but some of them require some thought.)

I can do this when I'm back in mid-Jan? 

And just to make sure we're on the same page: would you commit the individual releases (5.4.3, 5.4.4, etc.) or just the final one (5.4.6)? (Obviously, I don't want to waste time rebasing PRs that you don't plan to merge anyway!)

In addition to "merge intermediates" and "merge final" there's a third option: you could "merge final" without squashing. Then there'd be just one merge, but the intermediates would still be part of the history.

**Comment by mrdomino** [comment]
@michaellenaghan any updates on this?

@pkulchenko do you have any preferences on doing it in one PR vs multiple? FWIW I do not have much of a preference myself; if I had to call it one way or the other I'd probably say "merge final" for expedience's sake.

**Comment by pkulchenko** [comment]
One PR should be fine and would be my preference. I'd just commit 5.4.6 changes and wouldn't worry about the intermediate steps (as long as the end result is the same).

**Comment by michaellenaghan** [comment]
When I took another look at this in Jan it seemed like there were in fact so many changes that I'd effectively have to start from scratch. Given that the original PR was never accepted, I didn't know if that effort would pay off. Would it? (If @mrdomino is taking over the answer doesn't matter.)

**Comment by mrdomino** [comment]
I can't speak for anyone else, but when I first showed up I just ignored any PRs that had already been open when I arrived. Sorry about that.

Barring unforeseen circumstances (e.g. getting hit by a bus) I'll be around to make sure this gets reviewed and merged when the time comes. I would like to see this PR land. I was not planning on implementing it myself though.

**Comment by michaellenaghan** [comment]
OK, I'll put this back on my list and take a look next week. If I don't think I'll be able to complete it I'll let you know.

I have three other PRs (#868, #869, #870) that fixed timezone issues and were also overlooked. I rebased some of them at the end of last year, but... crickets. At this point I can't see trying again. Should I close them?

**Comment by mrdomino** [comment]
All right, sounds good, keep me posted.

I'll take a look at those PRs and see if there is anything to be done. I would request that you not close them yet.

**Comment by mrdomino** [comment]
@michaellenaghan just want to reiterate that I am sorry we were not able to integrate your contributions last time and also I would really like to have your help with the project.

One thing is that a lot of us usually hang out on [redbean discord](https://discord.gg/sN53mQMt), and we are not averse to being poked / harangued about stuff like PRs there. If something is not getting attention, do feel free to shout a bit about it.

**Comment by michaellenaghan** [comment]
Resolved in #1214.

**Pull request closed without merging**
