### PR TITLE
Add sqlite3 support to Lua scripts in Redbean

### PR DESCRIPTION
**Pull request by pkulchenko**
Opening this PR per discussion in https://github.com/jart/cosmopolitan/issues/97#issuecomment-855186562. I sent a separate email with copyright assignment.

### CODE REVIEW

**Comment by jart** [comment]
Good execution on this change. Thank you for your contribution. I'll push a new release of redbean to the website as soon as I have a chance.

**Comment by mskyttner** [comment]
Exciting work! I don't have deep knowledge of the codebase, but still dare to ask a couple of questions:

- It is very nice that inprocess sqlite3 persistence becomes part of redbean and sqlite3 has a (by default not compressed, I believe) storage format that is platform independent. With some of the (optional but widely used) sqlite3 extensions (such as the Full Text Search extension, FTS5), it could do a lot of what most need from a database. Including functioning as a "no-nosql" database with BLOBs. I would maybe even be the preferred choice for many. What will be the included extensions to sqlite3 embedded in redbean?
- For someone creating an actually portable executable with redbean and utilizing lua for dynamic server pages, where would/should database files be placed? And if such a web app would persist data not in memory but on disk, where would files be written?

**Comment by mskyttner** [comment]
Here is a demo from duckdb (similar to sqlite3 in many ways) with the TPC-H database: 

https://duckdb.org/demo/

The webapp source code is here:

https://github.com/duckdb/duckdb-web/tree/master/demo

What would be an outline of steps needed to do a similar demo with redbean and the TPC-H dataset?

**Comment by pkulchenko** [comment]
> What will be the included extensions to sqlite3 embedded in redbean?

@mskyttner, it looks like the following extensions are included (judging by the source code; I haven't tested any of them): FTS3, FTS5, JSON1, STMT, and RTree.

> For someone creating an actually portable executable with redbean and utilizing lua for dynamic server pages, where would/should database files be placed?

If the DB is read-only, my understanding that it can either be placed inside the redbean archive itself (with no compression) or outside of it.

> And if such a web app would persist data not in memory but on disk, where would files be written?

The DB file would need to be placed in a "protected" directory (similar to how the lua files are placed). I should be able to test that later today.

**Comment by pkulchenko** [comment]
> For someone creating an actually portable executable with redbean and utilizing lua for dynamic server pages, where would/should database files be placed? And if such a web app would persist data not in memory but on disk, where would files be written?

@mskyttner, I confirmed that when the DB file is referenced with a relative path (like `"test.db"`), it's created in the same directory as redbean itself (although I haven't tested the daemonized configuration).

**Pull request merged**
