### PR TITLE
Get hello.com working (again) for bare metal target: fix deterministic startup stack setup, implement __enable_tls()

### PR DESCRIPTION
**Pull request by tkchia**
This should partly address https://github.com/jart/cosmopolitan/issues/527 .

  * For the bare metal target, there should be no need for `libc/runtime/cosmo.S` to re-setup a stack at `ape_stack_vaddr` &mdash; since `ape/ape.S` has already done that anyway.  (And, `cosmo.S` should not clobber or corrupt any data that had been placed on the stack before.)
  * For other platforms, the code for aligning `%rsp` to a `ape_stack_align`-byte boundary did not look quite correct; so I have changed it.

Thank you!

### CODE REVIEW

**Comment by tkchia** [comment]
I also fixed `__enable_tls()` to work for the bare metal target.  On my build at least, `hello.com` now works, and says `hello world` on QEMU's emulated serial console.

Thank you!

**Review by jart — APPROVED** [review]
Nice! I love the TLS change especially. It makes me so happy to collaborate with someone on the bare metal support. Please consider joining our Discord so we can interact in real time. https://discord.gg/94A33huZ

Welcome as a new contributor. We need to go through one quick hurdle before we can proceed. Could you please email Justine Tunney <jtunney@gmail.com> and say that you intend to assign her the copyright to the changes you contribute to Cosmopolitan? Please send the email under your legal name rather than anonymously. Please put the URL of this pull request in the email. Please leave a comment on this PR saying you sent it. See [CONTRIBUTING.md](CONTRIBUTING.md) for further details. We make the ask because it helps us ship the tiniest most legally permissive prim and proper binaries. You also only need to do it one time, so any future changes you send us can be quickly merged.

**Comment by ghaerr** [comment]
Nice work, @tkchia!

> Thanks for bringing up the arch_prctl_msr() implementation — I had quite forgotten that newer x86-64's actually have special CPU registers to control the` %fs` and `%gs` base.

Out of curiosity, what happens when `wrmsr` is executed on bare metal on an older processor without that model-specific register? Is it just ignored, %fs and %gs base not changed, and TLS doesn't work?

> Please consider joining our Discord so we can interact in real time. https://discord.gg/94A33huZ

If you ever have time, that'd be great; there's been some discussions where your deep knowledge of gcc and x86 would be very helpful! :)

Thank you!

**Comment by tkchia** [comment]
Hello @jart,

> Welcome as a new contributor. We need to go through one quick hurdle before we can proceed. Could you please email Justine Tunney [jtunney@gmail.com](mailto:jtunney@gmail.com) and say that you intend to assign her the copyright to the changes you contribute to Cosmopolitan?

Thanks, I will send out the e-mail soon.

> Please consider joining our Discord so we can interact in real time. https://discord.gg/94A33huZ

Let me see if I can eke out some copious spare time. :slightly_smiling_face: 

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> Out of curiosity, what happens when `wrmsr` is executed on bare metal on an older processor without that model-specific register? Is it just ignored, %fs and %gs base not changed, and TLS doesn't work?

  * According to Intel's manuals ([q. v.](https://www.felixcloutier.com/x86/wrmsr)), `wrmsr` on an unimplemented MSR causes a CPU exception, so I guess that is what will happen.  (And if the OS kernel does not handle exceptions, then the CPU will ultimately triple-fault and reset itself.)
  * On 32-bit x86's, it has always been possible for the kernel to point `%fs` or `%gs` at an arbitrary 32-bit linear memory address, by crafting the appropriate GDT or LDT descriptor, and then loading`%fs`/`%gs`.

Thank you!

**Comment by tkchia** [comment]
Hello @jart,

I have sent you a copyright disclaimer e-mail.  Do let me know if there are any issues.  Thank you!

**Comment by jart** [comment]
@tkchia could you please bump the email and make sure a link to this pull request is in it? Also the phrase "copyright assignment". I just checked spam and my inbox and I don't see it.

**Comment by tkchia** [comment]
Hello @jart, I have sent the e-mail again.  Thank you!

**Comment by jart** [comment]
Confirmed! Thank you for sending it. Also thank you again for this change!

**Comment by tkchia** [comment]
Thanks @jart !

**Pull request merged**
