### PR TITLE
doc: remove "everything everything" from ParseUrl doc

### PR DESCRIPTION
**Pull request by fanquake**
Closes: #702.

### CODE REVIEW

**Review by jart — APPROVED** [review]
Thank you!

Could you send an email to jtunney@gmail.com saying "I intend to assign
you the copyright to the changes I contribute to Cosmopolitan" please?
See CONTRIBUTING.md. Please link to this GitHub pull request in your
email. Afterwards, please reply to this pull request saying "I sent
it!". I ask this of everyone. It only has to happen once. It only
applies to the changes you *choose* to contribute. We need it to protect
the project. The way we're protecting it is by keeping a record that
everyone's wishes are being respected. Please note that in order to
assign copyright, it has to be yours to assign. For example, if you have
a job where your employment contract states your employer owns
everything you do, then you can't assign copyright on your own. In that
case, what I recommend doing is writing an email to your manager telling
them what you're doing, and making sure he/she feels comfortable with
it. That way if an issue ever comes up, we'll have a record that you're
OK with the ownership of Cosmopolitan, and that your employer is OK with
it too.

**Comment by fanquake** [comment]
I sent it!

**Review by jart — APPROVED** [review]
Thank you again!

**Comment by jart** [comment]
Website updated.

**Pull request merged**
