### PR TITLE
Add support for storing folders in redbean from command line

### PR DESCRIPTION
**Pull request by pkulchenko**
@jart, changes to review:

- added ability to package folders recursively; `-A path/` adds all files in that folder (including `path/` in their path)
- changed `GetAsset` to `GetAssetZip`, as I think this correctly handles the case of the asset existing in the file system (stagedirs), but not in the archive: https://github.com/jart/cosmopolitan/compare/master...pkulchenko:redbean-add-dir?expand=1#diff-a937cc5818818785e079eab14ff76fa5db080fe9bd902d1ab21aa546aa79c7d1R3232
- added storing asset message with INFO level: https://github.com/jart/cosmopolitan/compare/master...pkulchenko:redbean-add-dir?expand=1#diff-a937cc5818818785e079eab14ff76fa5db080fe9bd902d1ab21aa546aa79c7d1R3202

### CODE REVIEW

**Review by jart — APPROVED** [review]
Looks good. In the future we may want to update this to use nftw(). https://github.com/jart/cosmopolitan/blob/master/examples/walk.c

**Comment by pkulchenko** [comment]
Sounds good; the current logic is based on https://github.com/jart/cosmopolitan/blob/master/examples/lstime.c#L41

**Comment by ahgamut** [comment]
`zip x.com ./a.txt` does the same thing as `zip x.com a.txt` 

I expect `StoreFile("./a.txt")` to do the same thing as `StoreFile("a.txt")`, but it doesn't.

**Comment by pkulchenko** [comment]
@ahgamut, are you suggesting the path to be normalized before being stored?

**Comment by pkulchenko** [comment]
@ahgamut, what does your wrapper do? Just drops leading `./`?

@jart, are you okay to drop leading `./` and check for `IsAcceptablePath()` after that, warn and skip?

**Comment by ahgamut** [comment]
@pkulchenko I wrote it like `StoreFile(path, target)` which reads data from `path` and calls `StoreAsset(target, strlen(target), ...)` [here](https://github.com/ahgamut/cosmopolitan/blob/storeasset-py/third_party/python/Python/cosmomodule.c#L232). If `target` is not provided, I try to construct it from `path`.

I like being able to choose/validate the target location inside the zip; it's useful in Python, but the tradeoffs may be different for redbean.

**Comment by pkulchenko** [comment]
@ahgamut, thank you for the suggestion! I submitted #373 that does this (among other things).

**Pull request merged**
