### PR TITLE
quickjs: add repl + qjscalc

### PR DESCRIPTION
**Pull request by agreppin**
1. added build rules to compile repl.js & qjscalc.js and include them in qjs.com
2. changed quickjs-libc.c / js_os_poll to handle the Windows console case

This last change is needed on Windows, because winsock/select can't be used on non-socket file descriptors, at least not yet.

### CODE REVIEW

**Review by jart — APPROVED** [review]
LGTM. Thank you for spotting this and taking the time to send a PR.

Also welcome as a new contributor. We need to go through one quick hurdle before I can merge. Could you please email Justine Tunney <jtunney@gmail.com> and say that you intend to assign her the copyright to the changes you contribute to Cosmopolitan? See [CONTRIBUTING.md](CONTRIBUTING.md) for further details. We make the ask because it helps us ship the tiniest most legally permissive prim and proper binaries. You also only need to do it one time, so any future changes you send us can be quickly merged.

Thanks!

**Comment by agreppin** [comment]
email sent on 19 august with subject cosmo copyrights attribution

**Comment by jart** [comment]
I'm sorry but I haven't received any email from you at jtunney@gmail.com and I checked my spam folder too. Could you please send it again?

**Comment by agreppin** [comment]
please, can you re-check as I sent it again from two different email addresses

**Comment by jart** [comment]
I'm sorry but I checked (including spam) and I haven't received any emails from you. If I do receive one, then I'll reopen. Sorry!

**Review by jart — APPROVED** [review]
Thank you!

**Pull request merged**
