### PR TITLE
Redbean getstatus and more

### PR DESCRIPTION
**Pull request by pkulchenko**
@jart, I added and renamed a couple of redbean methods. Feel free to remove renaming commits, but I think it looks more consistent with the new names. I marked those doing renames with "breaking change" comment in the commit message.

### CODE REVIEW

**Review by jart — CHANGES_REQUESTED** [review]
I'm happy to do this, but only if old names continue to be defined so existing code doesn't break. Also I intend to leave feedback on your design design ideas shortly in #97. Thanks you so much for your patience!

**Comment by jart** [comment]
With regard to breaking changes, please note the logging macros we changed earlier weren't publicly documented on the website, so they were strictly speaking an internal api and the commit message was intended as a courtesy to anyone who might have forked the cosmopolitan repo for their own internal needs, as a matter of courtesy. On the other hand APIs like `GetPayLoad()` are publicly and obviously documented on https://redbean.dev/ and are likely to be used. In the past, when renaming redbean functions like popcnt() to Popcnt() I kept the old ones around since there's little cost to doing so and it's a clear win for the user. Ultimately these things boil down to using our best judgement and consensus.

**Comment by pkulchenko** [comment]
Good point; I restored the two renamed methods and marked as "deprecated" in the docs.

**Review by jart — APPROVED** [review]
Looks good. It would also be sufficient to simply say ` (old name: GetPayload)`, but even that isn't strictly necessary. So long as old code written against publicly documented apis continues to run, we've done our job in terms of securing the user's time investments and can therefore evolve the best practices as much as we wish.

**Comment by jart** [comment]
Also for reference, here are links to the old versions of the docs maintained on the website:

- https://redbean.dev/1.3.html
- https://redbean.dev/0.4.html
- https://redbean.dev/0.3.html

I intend to keep doing that for each release to supplement the version control information.

**Pull request merged**
