### PR TITLE
third_party: Add libcxxabi

### PR DESCRIPTION
**Pull request by trungnt2910**
Added libcxxabi from LLVM 17.0.6
The library implements the Itanium C++ exception handling ABI.

The upstream library comes with a comprehensive test set, which I did _not_ add in this commit to prevent it from getting too large.

Part of  #1065.

### CODE REVIEW

**Review by jart — CHANGES_REQUESTED** [review]
There's already bits and pieces of cxxabi in the codebase.

- libc/cxxabi.h
- libc/runtime/cxaguard.c
- libc/thread/__cxa_thread_atexit.c

You need to figure out how to unify things so we don't have multiple implementations.

You also need to write a `README.cosmo` file for both libcxxabi and libunwind. If you make any changes to the source code, you need to document them in the `README.cosmo` file, under a section called `LOCAL MODIFICATIONS`.

**Comment by trungnt2910** [comment]
> You also need to write a README.cosmo file for both libcxxabi and libunwind. If you make any changes to the source code, you need to document them in the README.cosmo file, under a section called LOCAL MODIFICATIONS.

I believe that has already been done for this PR (https://github.com/jart/cosmopolitan/pull/1063/files#diff-023909efd99352e621d59379b348b643ec9309ad023c4ee780b38568c874a77a) as well as `libunwind` (https://github.com/jart/cosmopolitan/blob/master/third_party/libunwind/README.cosmo)

> There's already bits and pieces of cxxabi in the codebase.

This looks hard, unlike the unwind stubs, these implementations here look non-trivial and cannot be simply nuked away.

**Comment by trungnt2910** [comment]
> There's already bits and pieces of cxxabi in the codebase.

Done. The parts with complex implementations in cosmo are for `__cxa_thread_atexit_impl` and `__cxa_atexit`. These are also not implemented by `libcxxabi`.

Other parts are either trivial functions or other third-party code (`cxaguard`).

**Review by jart — APPROVED** [review]
OUTSTANDING. I'm loving it!

**Pull request merged**
