### PR TITLE
make rmrfdir use lstat() when d_type == DT_UNKNOWN

### PR DESCRIPTION
**Pull request by rtldg**
Made this pr for https://github.com/jart/cosmopolitan/issues/333

### CODE REVIEW

**Review by jart — CHANGES_REQUESTED** [review]
> Currently, only some filesystems (among them: Btrfs, ext2, ext3, and ext4) have full support for returning the file type in d_type. All applications must properly handle a return of DT_UNKNOWN.

#TIL 

Could you please update this change so that we preserve the optimization of `DT_DIR` in cases where it's available? Also...

Welcome as a new contributor. We need to go through one quick hurdle before we can proceed. Could you please email Justine Tunney <jtunney@gmail.com> and say that you intend to assign her the copyright to the changes you contribute to Cosmopolitan? Please send the email under your legal name rather than anonymously. See [CONTRIBUTING.md](CONTRIBUTING.md) for further details. We make the ask because it helps us ship the tiniest most legally permissive prim and proper binaries. You also only need to do it one time, so any future changes you send us can be quickly merged.

If you want, you may also want to update `third_party/musl/glob.c` but it's not required.

**Comment by rtldg** [comment]
> Could you please update this change so that we preserve the optimization of `DT_DIR` in cases where it's available? Also...

It checks that still on line 57 of the of the PR, which is reached if `d_type != DT_UNKNOWN`

> Welcome as a new contributor. We need to go through one quick hurdle before we can proceed. Could you please email Justine Tunney [jtunney@gmail.com](mailto:jtunney@gmail.com) and say that you intend to assign her the copyright to the changes you contribute to Cosmopolitan? Please send the email under your legal name rather than anonymously. See [CONTRIBUTING.md](CONTRIBUTING.md) for further details. We make the ask because it helps us ship the tiniest most legally permissive prim and proper binaries. You also only need to do it one time, so any future changes you send us can be quickly merged.

Sent

> If you want, you may also want to update `third_party/musl/glob.c` but it's not required.

It looks like it uses `DT_DIR` if available and will otherwise `stat()` if `!d_type` / `d_type == 0 (DT_UKNOWN)` so I don't think that needs any changes.

There still are a few other files where `DT_UKNOWN` is not further stat'ed though, do you want me to update those?

**Comment by jart** [comment]
Could you please reply to the email you sent me? I can't search for it in my inbox because your github profile doesn't have your name. Please be sure to link to this pull request in your email. Otherwise I won't be able to confirm it's you.

**Comment by rtldg** [comment]
> Could you please reply to the email you sent me? I can't search for it in my inbox because your github profile doesn't have your name. Please be sure to link to this pull request in your email. Otherwise I won't be able to confirm it's you.

Sent from the commit email (rtldg@protonmail.com)

**Comment by jart** [comment]
Thanks for sending that. It went to my spam folder but I fished it out. Do you have a corporate or home email address that isn't provided by an anonymous service?

**Comment by jart** [comment]
Closing due to inactivity. If you'd like to continue, let me know, and I'll reopen.

**Pull request closed without merging**
