### PR TITLE
GetServerAddr() won't crash redbean during init anymore

### PR DESCRIPTION
**Pull request by coderofsalvation**
big thanks for this very interesting piece of work

### CODE REVIEW

**Comment by pkulchenko** [comment]
@coderofsalvation, the current logic seems to be correct, as if I call `GetServerAddr` outside of the connection loop, I get the expected `GetServerAddr() can only be called while handling a connection` error. How does your minimal .init.lua code look like that leads to a crash? .init.lua is loaded ([LuaInit() call in RedBean function](https://github.com/jart/cosmopolitan/blob/master/tool/net/redbean.c#L6814)) before the connection is started (inside a later [HandleEvents() call in the same function](https://github.com/jart/cosmopolitan/blob/master/tool/net/redbean.c#L6841)). Am I missing something in this logic?

**Comment by coderofsalvation** [comment]
## .init.lua
```lua
local cfg  = require "cfg"
local util = require "util"
require "luafun" ()

-- special script called by main redbean process at startup
HidePath('/usr/share/zoneinfo/')
HidePath('/usr/share/ssl/')

local foo = GetServerAddr()   -- > this is where the shit hits the fan

```

## output

```bash
$ ./redbean.com -v -D . -- -foo=10
W2021-11-04T07:50:48.041126:tool/net/redbean.c:751:ffnode:1024681] certificate is expired

error: Uncaught SIGSEGV on ls540
  /home/leon/projects/ffnode.com/ffnode.com                                             
  ENOENT[2]                                                                             
  Linux ls540 5.11.0-38-generic #42-Ubuntu SMP Fri Sep 24 14:03:54 UTC 2021
                                                                                        
0x000000000040be65: GetServerAddr at tool/net/redbean.c:936
0x00000000004100e4: LuaGetAddr at tool/net/redbean.c:3296
0x000000000041011a: LuaGetServerAddr at tool/net/redbean.c:3303
0x00000000004d1644: luaD_precall at third_party/lua/ldo.c:512  
0x00000000004e9918: luaV_execute at third_party/lua/lvm.c:1610
0x00000000004d17e1: ccall at third_party/lua/ldo.c:557
0x00000000004d18c5: luaD_callnoyield at third_party/lua/ldo.c:575                                                                                                                
0x00000000004cb602: f_call at third_party/lua/lapi.c:1023
0x00000000004d0c21: luaD_rawrunprotected at third_party/lua/ldo.c:138
0x00000000004d1b05: luaD_pcall at third_party/lua/ldo.c:872                                                                                                                      
0x00000000004cca01: lua_pcallk at third_party/lua/lapi.c:1049
0x00000000004138da: LuaRun at tool/net/redbean.c:4332                                                                                                                            
0x0000000000415e19: LuaInit at tool/net/redbean.c:4482                                                                                                                           
0x000000000041b6e6: RedBean at tool/net/redbean.c:5677
0x000000000041bc01: main at tool/net/redbean.c:5751
0x00000000004018ea: cosmo at libc/runtime/cosmo.S:65                            
0x0000000000401173: _start at libc/crt/crt.S:67                                
                                                                                        
RAX 000000000040be56 RBX 0000100080002f88 RDI 00006ffffffffb1c ST(0) 0             
RCX 0000100080002f88 RDX 0000000000000000 RSI 00006ffffffffb1a ST(1) 0
RBP 00006ffffffffb00 RSP 00006ffffffffb00 RIP 000000000040be66 ST(2) 0               
R8  0000100080ac7ff0 R9  0000100080000000 R10 0000000000000003 ST(3) 0
R11 0000100080000000 R12 0000100080ac7fe0 R13 0000100080ab6570 ST(4) 0
R14 0000000000410108 R15 0000100080560cc0 VF IF PE

XMM0  ffffffffffffffffffffffffffffffff XMM8  00000001c6e415960000000154442bd4
XMM1  2e6e756661756c2f61756c2e3a70697a XMM9  202020205ca7bc63da521b1a7c7f204e
XMM2  00000000000044160000000000414845 XMM10 00000000000000000000000000000000
XMM3  00000000000000000000000000000000 XMM11 00000000000000000000000000000000
XMM4  00000000000000000000000000000000 XMM12 00000000000000000000000000000000
XMM5  000000009e122ea5a6d14e1425f0a9a0 XMM13 00000000000000000000000000000000
XMM6  726f707865206e72757465720a0a297d XMM14 00000000000000000000000000000000
XMM7  74657377617220202020202020202020 XMM15 00000000000000000000000000000000

mm->i == 7;
mm->p[  0]=={0x10008000,0x10008000,-1,3,34}; /* 1 */
mm->p[  1]=={0x10008001,0x10008053,-1,1,1}; /* 83 */
mm->p[  2]=={0x10008054,0x10008056,-1,3,34}; /* 3 */
mm->p[  3]=={0x10008057,0x10008057,-1,3,33}; /* 1 */
mm->p[  4]=={0x10008058,0x100080aa,-1,1,2}; /* 83 */
mm->p[  5]=={0x100080ab,0x100080ad,-1,3,34}; /* 3 */
/* 1,610,579,778 */
mm->p[  6]=={0x6ffffff0,0x6fffffff,12884901888,306,0}; /* 16 */
/* 190 frames mapped w/ 1,610,579,778 frames gapped */
00400000-00554000 r-xp 00000000 103:05 2388545                           /home/leon/projects/ffnode.com/ffnode.com
00554000-005a0000 rw-p 00000000 00:00 0 
100080000000-100080010000 rw-p 00000000 00:00 0 
100080010000-10008053b000 r--s 00000000 103:05 2388545                   /home/leon/projects/ffnode.com/ffnode.com
100080540000-100080570000 rw-p 00000000 00:00 0 
100080570000-100080580000 rw-s 00000000 00:01 605895                     /dev/zero (deleted)
100080580000-100080aab000 r--p 00000000 103:05 2388545                   /home/leon/projects/ffnode.com/ffnode.com
100080ab0000-100080ae0000 rw-p 00000000 00:00 0 
6ffffff00000-700000000000 rw-p 00000000 00:00 0 
7fff09308000-7fff0932a000 rw-p 00000000 00:00 0                          [stack]
7fff09366000-7fff0936a000 r--p 00000000 00:00 0                          [vvar]
7fff0936a000-7fff0936c000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]

```

**Comment by pkulchenko** [comment]
Is this on the current master? This doesn't happen for me (I commented out the first 3 lines) and could have been fixed in #300.

**Comment by pkulchenko** [comment]
@coderofsalvation, I noticed a log message in your output and judging by its content, it's definitely not the current master. Can you retest on the current master, as I suspect it already to be fixed?

**Comment by coderofsalvation** [comment]
Hi @pkulchenko, I think you are spot on:

```
$ git clone https://github.com/jart/cosmopolitan
$ cd cosmopolitan
$ git reset --hard
$ make -j16
$ unzip o/tool/net/redbean.com .init.lua
$ echo "GetServerAddr()" >> .init.lua
$ cat .init.lua
-- special script called by main redbean process at startup
HidePath('/usr/share/zoneinfo/')
HidePath('/usr/share/ssl/')
GetServerAddr()
$ zip o/tool/net/redbean.com .init.lua
updating: .init.lua (deflated 23%)
$ o/tool/net/redbean.com -v -D .
E2021-11-04T09:32:54.139861:tool/net/redbean.c:1031:redbean:1125045] (lua) failed to run lua code: /.init.lua:4: GetServerAddr() c
stack traceback:
[C]: in function 'GetServerAddr'
/.init.lua:4: in main chunk
```

I think I initially downloaded redbean.com from https://redbean.dev (which had the bug).
Then l added the line, compiled it..and assumed I fixed the bug *oops*.
Looking at the website, I now see that the binary *does* mention a commit-hash (which I assumed was master).
Thanks for pointing this out.

**Comment by pkulchenko** [comment]
Got it; thank you for the update. Just to explain a bit: `DontCallFromInitLua` didn't suffer from that issue (with throwing a Lua error), so adding it "fixed" the issue, but really masked the problem with the other call (which was already fixed).

**Pull request closed without merging**
